sudo: required
language: python
services:
- docker
python:
- '3.5'
install:
- pip install -r requirements.txt

script:
- python manage.py test

after_success:
- test $TRAVIS_BRANCH == "master" && docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD $DOCKER_URL && docker build -t $DOCKER_URL/slackbot:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER . && docker push $DOCKER_URL/slackbot:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER